// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADEUWyd7TcXIWcSEgbGkMr5gq1qQr09U8',
    appId: '1:674431584274:web:ff03e236fda7736b01b0cb',
    messagingSenderId: '674431584274',
    projectId: 'prueba-api-7bcb0',
    authDomain: 'prueba-api-7bcb0.firebaseapp.com',
    storageBucket: 'prueba-api-7bcb0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv3hWZ-3X6LjUsBSTYqgEOyWiBOG3bb60',
    appId: '1:674431584274:android:6128844bcb1bf7ce01b0cb',
    messagingSenderId: '674431584274',
    projectId: 'prueba-api-7bcb0',
    storageBucket: 'prueba-api-7bcb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUG6TzjrOTStiKn4SpTj8is7O8KYCCRQ0',
    appId: '1:674431584274:ios:25f39ebc12f1946b01b0cb',
    messagingSenderId: '674431584274',
    projectId: 'prueba-api-7bcb0',
    storageBucket: 'prueba-api-7bcb0.appspot.com',
    iosBundleId: 'com.example.flutterPracticeNavigationbar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUG6TzjrOTStiKn4SpTj8is7O8KYCCRQ0',
    appId: '1:674431584274:ios:925f7295a3dc2e9801b0cb',
    messagingSenderId: '674431584274',
    projectId: 'prueba-api-7bcb0',
    storageBucket: 'prueba-api-7bcb0.appspot.com',
    iosBundleId: 'com.example.flutterPracticeNavigationbar.RunnerTests',
  );
}
